/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is {cumented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments  * Retrieve a list of executed trades   # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	api "github.com/GIT_USER_ID/GIT_REPO_ID/api"
)

func main() {
	log.Printf("Server started")

	InstrumentsAPIService := api.NewInstrumentsAPIService()
	InstrumentsAPIController := api.NewInstrumentsAPIController(InstrumentsAPIService)

	OrderBooksAPIService := api.NewOrderBooksAPIService()
	OrderBooksAPIController := api.NewOrderBooksAPIController(OrderBooksAPIService)

	TradeOrderAPIService := api.NewTradeOrderAPIService()
	TradeOrderAPIController := api.NewTradeOrderAPIController(TradeOrderAPIService)

	TradesAPIService := api.NewTradesAPIService()
	TradesAPIController := api.NewTradesAPIController(TradesAPIService)

	router := api.NewRouter(InstrumentsAPIController, OrderBooksAPIController, TradeOrderAPIController, TradesAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
