/*
OPEN OUTCRY API

Testing UserAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"testing"

	openapiclient "open-outcry/demo/pkg/api"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_api_UserAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test UserAPIService CreateTrade", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string

		resp, httpRes, err := apiClient.UserAPI.CreateTrade(context.Background(), instrumentAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService DeleteTradeOrderById", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string
		var tradeOrderId string

		httpRes, err := apiClient.UserAPI.DeleteTradeOrderById(context.Background(), instrumentAccountId, tradeOrderId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService GetBookOrders", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string

		resp, httpRes, err := apiClient.UserAPI.GetBookOrders(context.Background(), instrumentAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService GetCurrencyAccounts", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var appEntityId string

		resp, httpRes, err := apiClient.UserAPI.GetCurrencyAccounts(context.Background(), appEntityId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService GetTradeById", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string
		var tradeId string

		resp, httpRes, err := apiClient.UserAPI.GetTradeById(context.Background(), instrumentAccountId, tradeId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService GetTradeOrderById", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string
		var tradeOrderId string

		resp, httpRes, err := apiClient.UserAPI.GetTradeOrderById(context.Background(), instrumentAccountId, tradeOrderId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService GetTradeOrders", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string

		resp, httpRes, err := apiClient.UserAPI.GetTradeOrders(context.Background(), instrumentAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService GetTrades", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string

		resp, httpRes, err := apiClient.UserAPI.GetTrades(context.Background(), instrumentAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test UserAPIService GetInstrumentAccount", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var instrumentAccountId string

		resp, httpRes, err := apiClient.UserAPI.GetInstrumentAccount(context.Background(), instrumentAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
