/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments * Retrieve a list of executed trades  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
	"open-outcry/pkg/models"
)

// AdminAPIService is a service that implements the logic for the AdminAPIServicer
// This service should implement the business logic for every endpoint for the AdminAPI API.
// Include any external packages or services that will be required by this service.
type AdminAPIService struct {
}

// NewAdminAPIService creates a default api service
func NewAdminAPIService() AdminAPIServicer {
	return &AdminAPIService{}
}

// CreateAdminTransfer - Create admin transfer
func (s *AdminAPIService) CreateAdminTransfer(ctx context.Context) (ImplResponse, error) {
	// Admin transfer creation requires a request body which is not passed through the interface.
	// Return not implemented for now since the controller doesn't parse a body for this endpoint.
	return Response(http.StatusNotImplemented, nil), nil
}

// GetAdminTransferById - Get transfer
func (s *AdminAPIService) GetAdminTransferById(ctx context.Context, transferId string) (ImplResponse, error) {
	transfer := models.GetTransfer(transferId)
	if transfer == nil {
		return Response(http.StatusNotFound, nil), nil
	}
	return Response(http.StatusOK, TransferEntry{
		Id:                      transfer.Id,
		Type:                    TransferType(transfer.Type),
		Amount:                  transfer.Amount,
		Currency:                string(transfer.Currency),
		SenderAccountId:         string(transfer.SenderAccountId),
		BeneficiaryAccountId:    string(transfer.BeneficiaryAccountId),
		Details:                 string(transfer.Details),
		ExternalReferenceNumber: string(transfer.ExternalReferenceNumber),
		Status:                  transfer.Status,
		DebitBalanceAmount:      transfer.DebitBalanceAmount,
		CreditBalanceAmount:     transfer.CreditBalanceAmount,
	}), nil
}

// GetAppEntities - Get application entities
func (s *AdminAPIService) GetAppEntities(ctx context.Context) (ImplResponse, error) {
	entities := models.GetAppEntities()
	var result []AppEntity
	for _, e := range entities {
		result = append(result, AppEntity{
			Id:         string(e.Id),
			ExternalId: string(e.ExternalId),
		})
	}
	return Response(http.StatusOK, result), nil
}

// GetAppEntity - Get application entity
func (s *AdminAPIService) GetAppEntity(ctx context.Context, appEntityId string) (ImplResponse, error) {
	entity := models.GetAppEntity(models.AppEntityId(appEntityId))
	if entity == nil {
		return Response(http.StatusNotFound, nil), nil
	}
	return Response(http.StatusOK, AppEntity{
		Id:         string(entity.Id),
		ExternalId: string(entity.ExternalId),
	}), nil
}
