/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is {cumented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments  * Retrieve a list of executed trades   # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// TradesAPIController binds http requests to an api service and writes the service results to the http response
type TradesAPIController struct {
	service TradesAPIServicer
	errorHandler ErrorHandler
}

// TradesAPIOption for how the controller is set up.
type TradesAPIOption func(*TradesAPIController)

// WithTradesAPIErrorHandler inject ErrorHandler into controller
func WithTradesAPIErrorHandler(h ErrorHandler) TradesAPIOption {
	return func(c *TradesAPIController) {
		c.errorHandler = h
	}
}

// NewTradesAPIController creates a default api controller
func NewTradesAPIController(s TradesAPIServicer, opts ...TradesAPIOption) Router {
	controller := &TradesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TradesAPIController
func (c *TradesAPIController) Routes() Routes {
	return Routes{
		"GetTrades": Route{
			strings.ToUpper("Get"),
			"/trades",
			c.GetTrades,
		},
	}
}

// GetTrades - trades list
func (c *TradesAPIController) GetTrades(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetTrades(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
