/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is {cumented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments  * Retrieve a list of executed trades   # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// TradeOrderAPIController binds http requests to an api service and writes the service results to the http response
type TradeOrderAPIController struct {
	service TradeOrderAPIServicer
	errorHandler ErrorHandler
}

// TradeOrderAPIOption for how the controller is set up.
type TradeOrderAPIOption func(*TradeOrderAPIController)

// WithTradeOrderAPIErrorHandler inject ErrorHandler into controller
func WithTradeOrderAPIErrorHandler(h ErrorHandler) TradeOrderAPIOption {
	return func(c *TradeOrderAPIController) {
		c.errorHandler = h
	}
}

// NewTradeOrderAPIController creates a default api controller
func NewTradeOrderAPIController(s TradeOrderAPIServicer, opts ...TradeOrderAPIOption) Router {
	controller := &TradeOrderAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the TradeOrderAPIController
func (c *TradeOrderAPIController) Routes() Routes {
	return Routes{
		"GetTradeOrders": Route{
			strings.ToUpper("Get"),
			"/trade_orders",
			c.GetTradeOrders,
		},
	}
}

// GetTradeOrders - trade order list
func (c *TradeOrderAPIController) GetTradeOrders(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetTradeOrders(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
