/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments * Retrieve a list of executed trades  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
	"open-outcry/pkg/models"
	"open-outcry/pkg/services"
)

// PublicAPIService is a service that implements the logic for the PublicAPIServicer
// This service should implement the business logic for every endpoint for the PublicAPI API.
// Include any external packages or services that will be required by this service.
type PublicAPIService struct {
}

// NewPublicAPIService creates a default api service
func NewPublicAPIService() PublicAPIServicer {
	return &PublicAPIService{}
}

// GetCurrencies - Currencies list
func (s *PublicAPIService) GetCurrencies(ctx context.Context) (ImplResponse, error) {
	currencies := models.GetCurrencies()
	var result []Currency
	for _, c := range currencies {
		result = append(result, Currency{
			Name:      string(c.Name),
			Precision: int32(c.Precision),
		})
	}
	return Response(http.StatusOK, CurrencyList{Data: result}), nil
}

// GetFxInstruments - Fx instrument list
func (s *PublicAPIService) GetFxInstruments(ctx context.Context) (ImplResponse, error) {
	instruments := models.GetFxInstruments()
	var result []FxInstrument
	for _, i := range instruments {
		result = append(result, FxInstrument{
			Id:            string(i.Id),
			Name:          string(i.Name),
			BaseCurrency:  string(i.BaseCurrency),
			QuoteCurrency: string(i.QuoteCurrency),
		})
	}
	return Response(http.StatusOK, result), nil
}

// GetInstruments - Instrument list
func (s *PublicAPIService) GetInstruments(ctx context.Context) (ImplResponse, error) {
	instruments := models.GetInstruments()
	var result []Instrument
	for _, i := range instruments {
		result = append(result, Instrument{
			Id:            string(i.Id),
			Name:          string(i.Name),
			QuoteCurrency: string(i.QuoteCurrency),
		})
	}
	return Response(http.StatusOK, result), nil
}

// GetOrderBook - Get order book
func (s *PublicAPIService) GetOrderBook(ctx context.Context, instrumentName string) (ImplResponse, error) {
	ob := services.GetOrderBook(models.InstrumentName(instrumentName))

	var sellSide []PriceVolume
	for _, pv := range ob.SellSide {
		sellSide = append(sellSide, PriceVolume{
			Price:  float32(pv.Price),
			Volume: float32(pv.Volume),
		})
	}

	var buySide []PriceVolume
	for _, pv := range ob.BuySide {
		buySide = append(buySide, PriceVolume{
			Price:  float32(pv.Price),
			Volume: float32(pv.Volume),
		})
	}

	var buySideInterface interface{} = buySide
	return Response(http.StatusOK, OrderBook{
		Sell: sellSide,
		Buy:  &buySideInterface,
	}), nil
}
