/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments * Retrieve a list of executed trades  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"net/http"
	"strings"
)

// CurrenciesAPIController binds http requests to an api service and writes the service results to the http response
type CurrenciesAPIController struct {
	service      CurrenciesAPIServicer
	errorHandler ErrorHandler
}

// CurrenciesAPIOption for how the controller is set up.
type CurrenciesAPIOption func(*CurrenciesAPIController)

// WithCurrenciesAPIErrorHandler inject ErrorHandler into controller
func WithCurrenciesAPIErrorHandler(h ErrorHandler) CurrenciesAPIOption {
	return func(c *CurrenciesAPIController) {
		c.errorHandler = h
	}
}

// NewCurrenciesAPIController creates a default api controller
func NewCurrenciesAPIController(s CurrenciesAPIServicer, opts ...CurrenciesAPIOption) Router {
	controller := &CurrenciesAPIController{
		service:      s,
		errorHandler: DefaultErrorHandler,
	}

	for _, opt := range opts {
		opt(controller)
	}

	return controller
}

// Routes returns all the api routes for the CurrenciesAPIController
func (c *CurrenciesAPIController) Routes() Routes {
	return Routes{
		"GetCurrencies": Route{
			strings.ToUpper("Get"),
			"/currencies",
			c.GetCurrencies,
		},
	}
}

// GetCurrencies - currencies list
func (c *CurrenciesAPIController) GetCurrencies(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.GetCurrencies(r.Context())
	// If an error occurred, encode the error with the status code
	if err != nil {
		c.errorHandler(w, r, err, &result)
		return
	}
	// If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
}
