/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments * Retrieve a list of executed trades  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
	"open-outcry/pkg/models"
	"open-outcry/pkg/services"
	"time"
)

// UserAPIService is a service that implements the logic for the UserAPIServicer
// This service should implement the business logic for every endpoint for the UserAPI API.
// Include any external packages or services that will be required by this service.
type UserAPIService struct {
}

// NewUserAPIService creates a default api service
func NewUserAPIService() UserAPIServicer {
	return &UserAPIService{}
}

// CreateTrade - Create trade order
func (s *UserAPIService) CreateTrade(ctx context.Context, instrumentAccountId string, req CreateTradeRequest) (ImplResponse, error) {
	orderId, err := services.ProcessTradeOrder(
		models.InstrumentAccountId(instrumentAccountId),
		models.InstrumentName(req.Instrument),
		models.OrderType(req.Type),
		models.OrderSide(req.Side),
		models.OrderPrice(req.Price),
		req.Amount,
		models.OrderTimeInForce(req.TimeInForce),
	)
	if err != nil {
		return Response(http.StatusBadRequest, nil), err
	}

	order := models.GetTradeOrder(orderId)
	return Response(http.StatusOK, mapTradeOrder(order)), nil
}

// DeleteTradeOrderById - Cancel trade order
func (s *UserAPIService) DeleteTradeOrderById(ctx context.Context, instrumentAccountId string, tradeOrderId string) (ImplResponse, error) {
	err := services.CancelTradeOrder(models.TradeOrderId(tradeOrderId))
	if err != nil {
		return Response(http.StatusNotFound, nil), err
	}
	return Response(http.StatusNoContent, nil), nil
}

// GetBookOrders - Get book orders
func (s *UserAPIService) GetBookOrders(ctx context.Context, instrumentAccountId string) (ImplResponse, error) {
	orders := models.GetBookOrdersByInstrumentAccount(models.InstrumentAccountId(instrumentAccountId))
	var result []TradeOrder
	for _, o := range orders {
		result = append(result, mapTradeOrder(o))
	}
	return Response(http.StatusOK, result), nil
}

// GetCurrencyAccounts - Get transfer accounts
func (s *UserAPIService) GetCurrencyAccounts(ctx context.Context, appEntityId string) (ImplResponse, error) {
	accounts := models.GetCurrencyAccountsByAppEntity(models.AppEntityId(appEntityId))
	var result []CurrencyAccount
	for _, a := range accounts {
		result = append(result, CurrencyAccount{
			Id:              string(a.Id),
			Currency:        string(a.Currency),
			Amount:          a.Amount,
			AmountReserved:  a.AmountReserved,
			AmountAvailable: a.AmountAvailable,
		})
	}
	return Response(http.StatusOK, CurrencyAccountList{Data: result}), nil
}

// GetTradeById - Get trade
func (s *UserAPIService) GetTradeById(ctx context.Context, instrumentAccountId string, tradeId string) (ImplResponse, error) {
	trade := models.GetTrade(tradeId)
	if trade == nil {
		return Response(http.StatusNotFound, nil), nil
	}
	return Response(http.StatusOK, Trade{Id: trade.Id}), nil
}

// GetTradeOrderById - Get trade order
func (s *UserAPIService) GetTradeOrderById(ctx context.Context, instrumentAccountId string, tradeOrderId string) (ImplResponse, error) {
	order := models.GetTradeOrder(models.TradeOrderId(tradeOrderId))
	return Response(http.StatusOK, mapTradeOrder(order)), nil
}

// GetTradeOrders - Get trade orders
func (s *UserAPIService) GetTradeOrders(ctx context.Context, instrumentAccountId string) (ImplResponse, error) {
	orders := models.GetTradeOrdersByInstrumentAccount(models.InstrumentAccountId(instrumentAccountId))
	var result []TradeOrder
	for _, o := range orders {
		result = append(result, mapTradeOrder(o))
	}
	return Response(http.StatusOK, result), nil
}

// GetTrades - Trades list
func (s *UserAPIService) GetTrades(ctx context.Context, instrumentAccountId string) (ImplResponse, error) {
	trades := models.GetTradesByInstrumentAccount(models.InstrumentAccountId(instrumentAccountId))
	var result []Trade
	for _, t := range trades {
		result = append(result, Trade{Id: t.Id})
	}
	return Response(http.StatusOK, result), nil
}

// GetInstrumentAccount - Get instrument account
func (s *UserAPIService) GetInstrumentAccount(ctx context.Context, instrumentAccountId string) (ImplResponse, error) {
	account := models.GetInstrumentAccount(models.InstrumentAccountId(instrumentAccountId))
	if account == nil {
		return Response(http.StatusNotFound, nil), nil
	}

	instruments := models.GetInstrumentAccountHoldings(models.InstrumentAccountId(instrumentAccountId))
	var apiInstruments []InstrumentAccountHolding
	for _, inst := range instruments {
		apiInstruments = append(apiInstruments, InstrumentAccountHolding{
			Name:            string(inst.Name),
			Amount:          inst.AmountAvailable + inst.AmountReserved,
			AmountReserved:  inst.AmountReserved,
			AmountAvailable: inst.AmountAvailable,
			Value:           inst.Value,
			Currency:        string(inst.Currency),
		})
	}

	return Response(http.StatusOK, InstrumentAccount{
		Id:          string(account.Id),
		Instruments: apiInstruments,
	}), nil
}

func mapTradeOrder(o models.TradeOrder) TradeOrder {
	created, _ := time.Parse(time.RFC3339Nano, o.Created)
	return TradeOrder{
		Id:          string(o.Id),
		Instrument:  string(o.InstrumentName),
		Side:        TradeOrderSide(o.Side),
		Type:        TradeOrderType(o.Type),
		TimeInForce: TradeOrderTimeInForce(o.TimeInForce),
		Status:      TradeOrderStatus(o.Status),
		Price:       float64(o.Price),
		Amount:      o.Amount,
		OpenAmount:  o.OpenAmount,
		Created:     created,
	}
}
