/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments * Retrieve a list of executed trades  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"errors"
	"net/http"
)

// TradesAPIService is a service that implements the logic for the TradesAPIServicer
// This service should implement the business logic for every endpoint for the TradesAPI API.
// Include any external packages or services that will be required by this service.
type TradesAPIService struct {
}

// NewTradesAPIService creates a default api service
func NewTradesAPIService() TradesAPIServicer {
	return &TradesAPIService{}
}

// GetTrades - trades list
func (s *TradesAPIService) GetTrades(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetTrades with the required logic for this service method.
	// Add api_trades_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, interface{}{}) or use other options such as http.Ok ...
	// return Response(200, interface{}{}), nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTrades method not implemented")
}
