/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is {cumented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments  * Retrieve a list of executed trades   # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

import (
	"context"
	"net/http"
	"errors"
)

// TradeOrderAPIService is a service that implements the logic for the TradeOrderAPIServicer
// This service should implement the business logic for every endpoint for the TradeOrderAPI API.
// Include any external packages or services that will be required by this service.
type TradeOrderAPIService struct {
}

// NewTradeOrderAPIService creates a default api service
func NewTradeOrderAPIService() TradeOrderAPIServicer {
	return &TradeOrderAPIService{}
}

// GetTradeOrders - trade order list
func (s *TradeOrderAPIService) GetTradeOrders(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetTradeOrders with the required logic for this service method.
	// Add api_trade_order_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []TradeOrder{}) or use other options such as http.Ok ...
	// return Response(200, []TradeOrder{}), nil

	// TODO: Uncomment the next line to return response Response(500, {}) or use other options such as http.Ok ...
	// return Response(500, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTradeOrders method not implemented")
}
