/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments * Retrieve a list of executed trades  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// PaymentAccountList - List of payment accounts available to user
type PaymentAccountList struct {
	Data []PaymentAccount `json:"data,omitempty"`
}

// AssertPaymentAccountListRequired checks if the required fields are not zero-ed
func AssertPaymentAccountListRequired(obj PaymentAccountList) error {
	for _, el := range obj.Data {
		if err := AssertPaymentAccountRequired(el); err != nil {
			return err
		}
	}
	return nil
}

// AssertPaymentAccountListConstraints checks if the values respects the defined constraints
func AssertPaymentAccountListConstraints(obj PaymentAccountList) error {
	return nil
}
