/*
 * OPEN OUTCRY API
 *
 * # Introduction This API is documented in **OpenAPI 3.0 format**.  This API the following operations: * Retrieve a list of available instruments * Retrieve a list of executed trades  # Basics * API calls have to be secured with HTTPS. * All data has to be submitted UTF-8 encoded. * The reply is sent JSON encoded.
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api

// PaymentAccount - Payment account available to user
type PaymentAccount struct {
	Id *interface{} `json:"id,omitempty"`

	// ISO 4217 Currency symbol
	Currency *interface{} `json:"currency,omitempty"`

	Amount *interface{} `json:"amount,omitempty"`

	AmountReserved *interface{} `json:"amountReserved,omitempty"`

	AmountAvailable *interface{} `json:"amountAvailable,omitempty"`
}

// AssertPaymentAccountRequired checks if the required fields are not zero-ed
func AssertPaymentAccountRequired(obj PaymentAccount) error {
	return nil
}

// AssertPaymentAccountConstraints checks if the values respects the defined constraints
func AssertPaymentAccountConstraints(obj PaymentAccount) error {
	return nil
}
